### ISSUE TITLE
Support for TypeScript

### ISSUE THREAD

**Issue by mikejcoop** [cedricdelpoux/gatsby-source-google-docs#102]
https://github.com/cedricdelpoux/gatsby-source-google-docs/blob/434c0bdb59ea0e9700616c19e898831dc6f2b9db/utils/create-pages.js#L6

We used TypeScript with our Gatsby project. The above line means that .tsx template files aren't picked up when resolving template path. Is this something you would consider adding support for?

**Comment by cedricdelpoux** [comment]
I don't use TypeScript but feel free to make a PR to support it. Thank you
