### ISSUE TITLE
Cannot read property 'metadata' of undefined

### ISSUE THREAD

**Issue by michaelpanik** [cedricdelpoux/gatsby-source-google-docs#107]
Every time I try to run `gatsby develop`, I'm getting the following error:

``` 
ERROR 

source-google-docs: Cannot read property 'metadata' of undefined

not finished source and transform nodes - 0.719s
not finished source-google-docs - 0.580s - fetching
```

And the process fails. What could I be doing wrong?

Gatsby @ 3.1.0, gatsby-source-google-docs @ 2.0.0

**Comment by cedricdelpoux** [comment]
Maybe in your `src` folder, you are using `metatada` the wrong way.

You can't query metadata. All metadata are spread into Google Docs nodes.

Use GraphiQL to see how to query it
