### ISSUE TITLE
Is there a way to style the images from the content of the doc

### ISSUE THREAD

**Issue by ilyador** [cedricdelpoux/gatsby-source-google-docs#108]
And do it without simply overriding the basic Gatsby classes like `gatsby-resp-image-wrapper`?

**Comment by linoxyn** [comment]
If you are bringing the images in with your HTML content query from the GoogleDocs then I believe you would have to override the image wrapper's style created within the markdownRemark plugin. If you query the images separately within GoogleDocs you could then control their styling completely with either gatsby-image or for Gatsby 3 use gatsby-plugin-image.

**Comment by cedricdelpoux** [comment]
If you want to style image directly from the content of a document, I believe there is no other way that using gatsby-image plugin classes unfortunately. 

Maybe with the new gatsby-image plugin there is a way to a custom classnames
