### ISSUE TITLE
Cover Image returns null 

### ISSUE THREAD

**Issue by linoxyn** [cedricdelpoux/gatsby-source-google-docs#119]
I have updated gatsby-source-google-docs to version `^2.0.4` and I have found that the **cover** image cannot be returned. I am using the latest Gatsby V3. 

An example of a query:

```
pagecontent: allGoogleDocs(
      filter: { category: { eq: "technique step" }, exclude: { eq: false } }
      sort: { fields: childrenMarkdownRemark___frontmatter___order, order: ASC }
    ) {
      nodes {
        id
        pagetitle
        order
        cover {
          image {
            childImageSharp {
              gatsbyImageData(
                width: 500
                placeholder: DOMINANT_COLOR
                formats: [AUTO, WEBP, AVIF]
              )
            }
          }
          alt
        }
        childMarkdownRemark {
          html
        }
      }
    }
```

I get the error **Cannot read property 'childImageSharp' of null**  I have no problems when I query and the images all return from the body of a document. 

Thank you for your help.

**Comment by cedricdelpoux** [comment]
Nice catch. Could you try the last `v2.1.1`? Thank you

**Comment by linoxyn** [comment]
Updated and up and running! Thank you for your quick response! 😎
