### ISSUE TITLE
gatsby-source-google-docs-token command not found

### ISSUE THREAD

**Issue by tombassrosenfeld** [cedricdelpoux/gatsby-source-google-docs#120]
Hi, 

I've set up a clean gatsby project and followed the installation guide in the readme. 

The command ```gatsby-source-google-docs-token``` is not being found. 

I'm in the process of manually setting up the oauth. It's not straightforward. 

Using mac on os 11.4.

Any suggestions? 

Thanks.

**Comment by nfmastroianni** [comment]
In your package.json file add a line in the scripts object
```javascript
scripts: {
// all your other scripts
"getToken": "gatsby-source-google-docs-token",
}
```
then you can run npm run getToken. I use yarn getToken.

**Comment by tombassrosenfeld** [comment]
Thanks for this. I'll take a look.

**Comment by cedricdelpoux** [comment]
Hi @tombassrosenfeld, sorry for the delay. @nfmastroianni is right, it should solve your issue. Thanks for helping
