### ISSUE TITLE
images are not downloaded and instead all link to googleusercontent.com URLs

### ISSUE THREAD

**Issue by gtnbssn** [cedricdelpoux/gatsby-source-google-docs#125]
From reading other closed issues it seems the image should indeed be downloaded and served locally

https://github.com/cedricdelpoux/gatsby-source-google-docs/issues/67

I hadn't noticed the issue during the testing phase as images were usually showing, but it turns out they all have an src attribute pointing to googleusercontent. All my source documents have cover images, and these however are always properly downloaded. But the images in the flow of the document always generate plain img elements with an src attribute pointing to googleusercontent, and very often do not display on the site.

**Comment by cedricdelpoux** [comment]
Hi @gtnbssn , sorry for the delay. Thank you for investigating. I just published a fix in `2.1.2` version

**Comment by gtnbssn** [comment]
Works great, thank you so much!
