### ISSUE TITLE
ERROR: The service is currently unavailable

### ISSUE THREAD

**Issue by harshitsan** [cedricdelpoux/gatsby-source-google-docs#127]
From the 14th of September, it's not working anymore.
can't understand why it's happening

Console error
![image](https://user-images.githubusercontent.com/30543655/133672107-76d46dfe-b3ce-4be8-997a-96dc8d0d60d6.png)

Errors from google docs API metrics

[Errors by API method (1).csv](https://github.com/cedricdelpoux/gatsby-source-google-docs/files/7180456/Errors.by.API.method.1.csv)

**Comment by cedricdelpoux** [comment]
Strange it's working for me. Could you try to generate a new token?

**Comment by cedricdelpoux** [comment]
Strange it's working for me. Could you try to generate a new token?

**Comment by harshitsan** [comment]
Actually, I got the solution as this error came from google API, there's no issue in the plugin.
Thanks
