### ISSUE TITLE
Fetch images from google docs and transform them to gatsby local nodes

### ISSUE THREAD

**Issue by cedricdelpoux** [cedricdelpoux/gatsby-source-google-docs#13]
Actually, it seems to me that some images are visible only if we are login to google and have rights to see documents.

It could be nice to use the official [gatsby-source-filesystem](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-source-filesystem) and the `createRemoteFileNode` to fetch images and transform them to gatsby nodes.

I'm not sure how to do this.

What do you think @KyleAMathews ?

**Comment by KyleAMathews** [comment]
yeah! I think making this optional would be great — if the site is intended to be public — it'd be best to download the images to ensure everyone can visit them — then also we could use gatsby-remark-images to make images responsive as some people will add enormous images to their google docs.

Here's the docs for createRemoteFileNode https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-source-filesystem#createremotefilenode

I can help with an implementation

**Comment by xuopled** [comment]
Nice!

**Comment by dmouse** [comment]
hello folks, also, if is posible get the `Alt text`

Thanks for this amazing plugin :)

**Comment by victsant** [comment]
Is there any update on this?

**Comment by xuopled** [comment]
I'm not sure how to do this. Any help would be awesome 💪🏻

**Comment by dmouse** [comment]
I think that in [this line](https://github.com/xuopled/gatsby-source-google-docs/blob/master/src/utils/convert-google-document-to-json.js#L136) you can execute the download for each image

**Comment by KyleAMathews** [comment]
And here's the docs for the createRemoteFileNode helper you'll want to use.

https://www.gatsbyjs.org/packages/gatsby-source-filesystem/?=file#createremotefilenode

**Comment by victsant** [comment]
Raised a PR https://github.com/xuopled/gatsby-source-google-docs/pull/22 for this as I need it for a current project.

**Comment by xuopled** [comment]
Thank you @victsant for your work. 

@KyleAMathews, could you review the PR ?

Just wondering if there is a way with createRemoteFileNode to fetch external images and to download them into a folder. Then, we could only need to replace absolute urls with relative ones.

Replace:
```
Some text with an ![image](https://random-absolute-url-image.jpg)
```

By:
```
Some text with an ![image](../relative-image.jpg)
```

**Comment by xuopled** [comment]
I merged the PR but the discussion about this can continue here

**Comment by KyleAMathews** [comment]
Yup! You can definitely replace the absolute URL with one linking to the downloaded image. This is similar to what this plugin does https://www.gatsbyjs.org/packages/@weknow/gatsby-remark-drupal/

This would allow gatsby-remark-images to make the images responsive.

**Comment by xuopled** [comment]
Thank you Kyle, I will see what I can do

**Comment by cedricdelpoux** [comment]
It is fixed in `2.x.x-beta` version
