### ISSUE TITLE
Documentation links broken

### ISSUE THREAD

**Issue by bigprosody** [cedricdelpoux/gatsby-source-google-docs#139]
Haven't had the opportunity to actually look into why, but every link on the documentation website is broken. See: [Example](https://cedricdelpoux.github.io/codes). (The main page seems to be working just fine.)

**Comment by cedricdelpoux** [comment]
Yes sorry! It seems like `pathPrefix` are not working with *Gatsby v4*. I need to find a way to fix it. Any help is appreciated

**Comment by cedricdelpoux** [comment]
Thanks for reporting this. I fixed the documentation website. Pages were not prefixed with `/gatsby-source-google-docs`
