### ISSUE TITLE
Images I put in the document become links

### ISSUE THREAD

**Issue by ilyador** [cedricdelpoux/gatsby-source-google-docs#140]
For some reason, any image I insert in the google doc is transformed to be wrapped in an `<a>` linking to the image. How do I prevent that?

**Comment by cedricdelpoux** [comment]
If you use `gatsby-remark-images`, you need to set `linkImagesToOriginal` option to `false`.

```
   {
      resolve: "gatsby-remark-images",
      options: {
        linkImagesToOriginal: false,
      },
    }
```
