### ISSUE TITLE
Gatsby build hanging on source-google-docs - fetching

### ISSUE THREAD

**Issue by aaronaustin** [cedricdelpoux/gatsby-source-google-docs#141]
This just started last night without any changes to the code.  My site isn't building anymore (locally, or on Gatsby cloud).  It's hanging up after the console reads: `⠼ source and transform nodes ⠼ source-google-docs — fetching Google Docs documents`.  I just ran through a bunch of updates and the same issues are still happening.  I'm not sure what would cause this change.  Any help appreciated.

**Comment by aaronaustin** [comment]
I got things to build again.  There's something in one of my newest docs that was causing a problem.  I'll have to do some more work to track it down.  Sorry for the false alarm. Thanks for a great plugin!

**Comment by alibalbars** [comment]
I encoured the same problem. When i add google document to the drive folder and fill the content by myself, Its working well. But when i copy paste the content from another document, the terminal stays at ```source-google-docs — fetching Google Docs documents``` line. Then when i removed the copy pasted document, build was successful again.

I dont understand why it happens. I would be glad if you help
