### ISSUE TITLE
Build hanging on `fetching Google Docs documents`

### ISSUE THREAD

**Issue by alibalbars** [cedricdelpoux/gatsby-source-google-docs#143]
When i add google document to the drive folder and fill the content by myself, Its working well. But when i copy paste the content from another document, the build hanging on ```source-google-docs — fetching Google Docs documents``` line. Then when i removed the copy pasted content (making the document empty), build was successful again.

I dont understand why it happens. I would be glad if you help.

```
"dependencies": {
    "@mdx-js/mdx": "^1.6.22",
    "@mdx-js/react": "^1.6.22",
    "@reach/router": "^1.3.4",
    "gatsby": "^4.4.0",
    "gatsby-plugin-create-client-paths": "^4.4.0",
    "gatsby-plugin-image": "^2.4.0",
    "gatsby-plugin-mdx": "^3.4.0",
    "gatsby-plugin-sass": "^5.4.0",
    "gatsby-plugin-sharp": "^4.4.0",
    "gatsby-remark-images": "^6.4.0",
    "gatsby-source-filesystem": "^4.4.0",
    "gatsby-source-google-docs": "^2.2.0",
    "gatsby-transformer-sharp": "^4.4.0",
    "react": "^17.0.1",
    "react-dom": "^17.0.1",
    "react-router-dom": "^5.0.0",
    "sass": "^1.45.0",
    "theme-ui": "^0.12.0"
  }
```

**Comment by alibalbars** [comment]
After trying copy from some other contents this problem not occured. Maybe the problem caused by the pasted specific content. Thanks for this awesome plugin <3

**Comment by cedricdelpoux** [comment]
Please share a document if you have the problem in the futur
