### ISSUE TITLE
GoogleDocument.getTableCellContent fails on empty cells

### ISSUE THREAD

**Issue by AlberErre** [cedricdelpoux/gatsby-source-google-docs#149]
Hey all,

We're facing an issue while parsing docs with empty content on table cells.

Looks like `GoogleDocument.getTableCellContent` method fails when the cell content is empty. 

![image](https://user-images.githubusercontent.com/20255458/150338259-a5f10948-d0a8-4f52-ab95-aa4e9df17135.png)

Thanks!

**Comment by AlberErre** [comment]
We've added a PR fixing this issue #150

**Comment by cedricdelpoux** [comment]
Thanks, I will publish a new version in few days
