### ISSUE TITLE
Trigger Gatsby Build

### ISSUE THREAD

**Issue by ehannes** [cedricdelpoux/gatsby-source-google-docs#153]
Thanks for a great plugin @cedricdelpoux!

I just wonder how your [Gatsby Build Trigger](https://docs.google.com/spreadsheets/d/1cA53xibP-WbMocWeZGs9FhUnshio7xAEn6ESqNiWTlk/edit#gid=0) works. I can see you have added a "Build" button, but I can't see how it's working (is it working by the way?). Would be really nice to learn how that works (or is intended to be working).

Thanks

**Comment by cedricdelpoux** [comment]
Hi @ehannes,

Yes it works. You need to copy the build hook URL from Gatsby Cloud (or Netlify) and assign it to the button action.

You need to copy the script I put in the documentation and adapt it to your need
