### ISSUE TITLE
Problem with gatsby-source-google-docs-token

### ISSUE THREAD

**Issue by jasiek-net** [cedricdelpoux/gatsby-source-google-docs#180]
When I run this script I have screen "Configure OAuth consent screen", is there any instruction how to configure oauth consent screen? I tried to configure consent screen, but then I got this error on authorization:
<img width="473" alt="image" src="https://user-images.githubusercontent.com/9372463/177328079-2250b1e4-48b8-4da1-b651-a1bf62937bca.png">

**Comment by jasiek-net** [comment]
Ok, I found out solution:

- Open google cloud
- Go to "Credentials" tab
- Click go generated client Id (tabel "OAuth 2.0 Client IDs)
- Add "Authorized redirect URIs": http://localhost:5000, http://localhost:5000/callback, http://localhost:5000/oauth-authorized/google
- Save and try login again!

![image](https://user-images.githubusercontent.com/9372463/177356330-1f3769b2-a8f5-4bf4-98b7-30ff0ec254a8.png)

**Comment by cedricdelpoux** [comment]
You found the trick 👍🏻
