### ISSUE TITLE
Documentation: issue with copying google drive

### ISSUE THREAD

**Issue by ethanstrominger** [cedricdelpoux/gatsby-source-google-docs#189]
From documentation: `Create a copy of Trigger Gatsby Build file using Right Click -> Create a copy`

Create a copy did not show up as an option.  I googled and could not find a simple way to copy a Google drive.
![image](https://user-images.githubusercontent.com/32078396/181826048-62409ad1-ddab-4864-9df9-02c8421e9240.png)

**Comment by cedricdelpoux** [comment]
Google Drive changed this. Could you change the doc? Thanks

**Comment by cedricdelpoux** [comment]
I can't reproduce. "Make a copy" is available for me from an other Google account:
<img width="618" alt="Screenshot 2022-09-18 at 08 55 05" src="https://user-images.githubusercontent.com/2683300/190889913-37e6cac8-82a0-43b2-8cc0-2acad48f972e.png">
