### ISSUE TITLE
Documentation: More details needed for webhook and what is A2? 

### ISSUE THREAD

**Issue by ethanstrominger** [cedricdelpoux/gatsby-source-google-docs#191]
From the documentation: `Open your copy and update the Build Webhook URL in A2`

I can modify documentation to address these issues:

- add URL for how to set up Webhooks https://developers.google.com/drive/api/guides/push
- change "A2" => "root folder for documents that are being converted."

**Comment by cedricdelpoux** [comment]
Yes, please modify! Thank you for your help
