### ISSUE TITLE
Documentation: reporter

### ISSUE THREAD

**Issue by ethanstrominger** [cedricdelpoux/gatsby-source-google-docs#193]
The main function includes a reporter parameter:
```
exports.sourceGDocs2MD = async (
  {actions: {createNode}, createContentDigest, reporter},
```

Is there code or a yarn package for the reporter?  I created a reporter class that works and basically does some simple time calculations and console.log.

**Comment by cedricdelpoux** [comment]
reporter is a Gatsby node helper: https://www.gatsbyjs.com/docs/reference/config-files/node-api-helpers/#GatsbyReporter
