### ISSUE TITLE
Simple wrapper to save markdown files locally (with images)

### ISSUE THREAD

**Issue by jasiek-net** [cedricdelpoux/gatsby-source-google-docs#196]
Hi!
Thanks for a great lib, I've been using it for several weeks, however I needed something to save markdown files locally, so I created simple wrapper that replaces Gatsby functions with custom logic. It's written in two evenings and it's really basic, but maybe someone needs this functionality as well:

https://github.com/jasiek-net/google-docs-to-markdown

Thanks again, I couldn't find anything better on Github to scrap Google Drive recursively, the code is great and readable, my script is shit, but work in progress ;)

**Comment by cedricdelpoux** [comment]
Thanks for sharing, it could be useful 👍🏻
