### ISSUE TITLE
Support @Person and rich link (chips)

### ISSUE THREAD

**Issue by n3v3rf411** [cedricdelpoux/gatsby-source-google-docs#201]
These are relatively new features on Google Docs and easy to support. I have a small PR ready but would be great to add tests by adding to the Google Docs used like [links](https://docs.google.com/document/d/1UuBxtIEEVh98wyBR9fMmLqzJEkmNlAMMoC4SEhprHfQ/preview).

**Comment by cedricdelpoux** [comment]
Thanks @n3v3rf411. I just merged it. Feel free to add test later!
