### ISSUE TITLE
Can't fetch images anymore

### ISSUE THREAD

**Issue by ehannes** [cedricdelpoux/gatsby-source-google-docs#223]
Hi!

I've been using this plugin for quite some time now. Suddenly, I get this error when fetching images from Google Docs. I haven't changed my credentials and the text is still fetched, it's just the images that fails. After the "source and transform nodes" step is done, the plugin reports: `success source-google-docs - 66.422s - 22 documents and 0 images fetched`.

This might be related to https://github.com/cedricdelpoux/gatsby-source-google-docs/issues/222, but in contrast to that error report I do get errors in development (a lot of errors). Also, the `gatsby build` command succeeds.

I'm using `gatsby-source-google-docs@2.4.1` and `gatsby@4.25.6`.

Here's an example of how the error looks like. I get one per image that should have been fetched.

```
warn source-google-docs: HTTPError: Unable to fetch:
https://lh3.googleusercontent.com/docs/example-id
---
Reason: Response code 403 (Forbidden)
---
Fetch details:
{
  "attempt": 3,
  "method": "GET",
  "errorCode": "ERR_NON_2XX_3XX_RESPONSE",
  "responseStatusCode": 403,
  "responseStatusMessage": "Forbidden",
  "requestHeaders": {
    "user-agent": "got (https://github.com/sindresorhus/got)",
    "accept-encoding": "gzip, deflate, br"
  },
  "responseHeaders": {
    "content-type": "text/html; charset=UTF-8",
    "x-content-type-options": "nosniff",
    "content-encoding": "gzip",
    "date": "Mon, 01 May 2023 14:49:25 GMT",
    "server": "fife",
    "cache-control": "private",
    "x-xss-protection": "0",
    "alt-svc": "h3=\":443\"; ma=2592000,h3-29=\":443\"; ma=2592000",
    "connection": "close",
    "transfer-encoding": "chunked"
  }
}
```

**Comment by cedricdelpoux** [comment]
Yes it's related to https://github.com/cedricdelpoux/gatsby-source-google-docs/issues/222. I did not have time recently to investigate but I fixed an issue about the token Could you try re-generate one?

**Comment by ehannes** [comment]
@cedricdelpoux thanks for your answer. I'll try that.
