### ISSUE TITLE
❌GOOGLE_DOCS_TOKEN

### ISSUE THREAD

**Issue by jothikannan89** [cedricdelpoux/gatsby-source-google-docs#238]
❌GOOGLE_DOCS_TOKEN always says not valid

I have followed the below steps to get the GOOGLE_DOCS_TOKEN 
1. Enabled Google Drive and Docs API in the google console
2. Created OAuth2 Client ID and Secret key
3. Using OAuth 2.0 Playground I have created the Access and Refresh token for my own OAuth Credentials
as said in the below reference 
https://help.talend.com/r/en-US/8.0/google-drive/how-to-access-google-drive-using-client-id-and-secret-a-google

**Comment by jothikannan89** [comment]
no worried, fixed it myself

**Comment by cedricdelpoux** [comment]
What was the problem?
