### ISSUE TITLE
Unclear setup instrunctions

### ISSUE THREAD

**Issue by dandv** [cedricdelpoux/gatsby-source-google-docs#37]
The instructions say to turn ON two APIs, then,

> Get a client_id and a client_secret from the Google console.

![image](https://user-images.githubusercontent.com/33569/67318179-c19a4a80-f4d0-11e9-9107-b3a67a5d9b0f.png)

Which one? There are two `client_id` and `client_secret` at this point, one from Drive,

![image](https://user-images.githubusercontent.com/33569/67318740-7b91b680-f4d1-11e9-9c4a-c710b218393d.png)

...and one from Docs:

![image](https://user-images.githubusercontent.com/33569/67318809-96fcc180-f4d1-11e9-821a-198817d76974.png)

Then the instructions say,

> Get an `api_key` from the Google console

Must the developer go to the Google Console, or can they click the "Create API key" button on the [Docs page](https://developers.google.com/docs/api/quickstart/js) they're already on?

I tried putting the Docs credentials in the plugin configuration, then I ran into another source of confusion: setting or generating the token. Leaving the sample config unchanged except for `config/client_id` and `config/client_secret`, I ran `gatsby develop`, and got this error:

> "gatsby-source-google-docs" threw an error while running the sourceNodes lifecycle:
> 
> source-google-docs: Unexpected token o in JSON at position 1

**Comment by cedricdelpoux** [comment]
You should try to take those from the Google Drive Api

**Comment by cedricdelpoux** [comment]
New API and new doc in `2.x.x-beta` version. Please try it :)
