### ISSUE TITLE
Create node field for folder names

### ISSUE THREAD

**Issue by justinsunho** [cedricdelpoux/gatsby-source-google-docs#38]
It would be nice to have the 'un-kebabcased', normal folder names available for each node to help with building out navigations. 

Right now, we're using the paths to build out a tree for a navigation, but if we had an array of a doc's parent folder names, it would help with properly displaying the names in a navigation and would save us the step of having to parse through the given paths created.

**Comment by justinsunho** [comment]
as a work-around, we're 'start casing' the kebab cased values given to use through the path

ex. `landing-page-builder` -> `Landing Page Builder`

**Comment by cedricdelpoux** [comment]
It's a good idea to let the user decide wich algorithm to use to generate folder names. 

Could you make a PR for that?

**Comment by justinsunho** [comment]
hey cedric! thanks for the active engagement, really appreciate the plugin. I'll try my best to make a PR. I have some more bugs/feature requests I'll be making though.

**Comment by cedricdelpoux** [comment]
Thank you for your help 🙏🏻

**Comment by cedricdelpoux** [comment]
It is fixed in `2.x.x-beta` version.

Please checkout [the documentation](https://github.com/cedricdelpoux/gatsby-source-google-docs/blob/master/docs/faq.md#how-can-i-get-a-breadcrumb) to know how to get a breadcrumb
