### ISSUE TITLE
Inserted Page Breaks after lists cause build errors

### ISSUE THREAD

**Issue by justinsunho** [cedricdelpoux/gatsby-source-google-docs#40]
When I insert a page break after a list, `command + enter` or `insert > break > page break`, I get these build errors:

```
TypeError: Cannot read property 'content' of undefined

  - convert-google-document-to-json.js:43 getText
    [lfris-marketing-docs]/[gatsby-source-google-docs]/utils/convert-google-document-to-json.js:43:40
```

Note: this doesn't happen with 'natural' page breaks that are created by content

**Comment by cedricdelpoux** [comment]
It is fixed in `2.x.x-beta` version
