### ISSUE TITLE
Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by jhthompson** [cedricdelpoux/gatsby-source-google-docs#42]
After following the setup instructions and authenticating through the Google Drive API I am getting the following error message: 

---
ERROR #11321  PLUGIN

"gatsby-source-google-docs" threw an error while running the sourceNodes lifecycle:

source-google-docs: Cannot read property 'name' of undefined

  Error: source-google-docs: Cannot read property 'name' of undefined
  
  - gatsby-node.js:111 Object.exports.sourceNodes
    [google-docs-gatsby-test]/[gatsby-source-google-docs]/gatsby-node.js:111:10
  
  - task_queues.js:94 processTicksAndRejections
    internal/process/task_queues.js:94:5

warn The gatsby-source-google-docs plugin has generated no Gatsby nodes. Do you need it?

---

Any ideas what could be causing this?

**Comment by justinsunho** [comment]
it's something to do with your google docs itself. It's very difficult to know without knowing is in your google drive tho

**Comment by jhthompson** [comment]
Is there a certain format that the Google Doc(s) need to be written in? Or does it sound like this is related to a setting with the authentication / sharing? I have one Google Doc in one folder in my Drive at the moment.

**Comment by justinsunho** [comment]
No specific format, but some content formatting does break the build step, like https://github.com/cedricdelpoux/gatsby-source-google-docs/issues/40 or https://github.com/cedricdelpoux/gatsby-source-google-docs/issues/39

**Comment by justinsunho** [comment]
is your repo private?

**Comment by jhthompson** [comment]
Currently private, yes

**Comment by jhthompson** [comment]
The Google account I am using is one from a university that uses Google Apps for Education, not sure if that would affect things in any way or not

**Comment by justinsunho** [comment]
it could be that, but since you were able to generate the proper keys it doesn't seem to be an issue with permissioning, but if that's your hunch you should probably use a different account that you have permissions for?

**Comment by jhthompson** [comment]
I'll try with a personal Google account and see if the issue persists

**Comment by justinsunho** [comment]
or do you have any content in your doc? it's on the sourcing step so the keys do work

**Comment by jhthompson** [comment]
I have some text and an unordered list with three sentences

**Comment by jhthompson** [comment]
Also, using my personal Google account for everything still gives the same error, so definitely doesn't seem to be a permissions/auth issue, you're right

**Comment by jhthompson** [comment]
Update: things seem to work when I include all of the below "Optional" configuration settings in the file. I had them commented out as I thought they wouldn't affect things but leaving them out in various combinations seems to break things in different ways.

//Optional\
// --------\
        fields: ["createdTime"], // https://developers.google.com/drive/api/v3/reference/files#resource\
        fieldsMapper: { createdTime: "date", name: "title" }, // To rename fields\
        fieldsDefault: { draft: false }, // To add default fields values\
        convertImgToNode: true, // To convert images to remote node files\
        debug: true, // To display folders names\
        timeBetweenCalls: 2000, // To prevent reaching Google api short limits

**Comment by justinsunho** [comment]
after testing it myself, seems like you'd only need `fields` and `fieldsMapper`. That makes sense since `fieldsMapper` has the name property.

I'd probably remove the other options though since it might create more unforseen issues.

**Comment by linoxyn** [comment]
I had to remove the name property to avoid this error, even with all the options in place. I believe it's conflicting with the Google api naming for the doc ?:-/ 

`fieldsMapper: { createdTime: "date" }, // To rename fields `

The readme file states `node.frontmatter.name` contains the title of the Google Doc

**Comment by jhthompson** [comment]
Yes I realized I had to do the same thing as you @linoxyn , it only worked for me once I removed the name property from `fieldsMapper`

**Comment by cedricdelpoux** [comment]
if you choose to rename `name` to `title` with `fieldsMapper: {name: "title"}`, then you have to query and use `title`

```
    query BlogPostBySlug($slug: String!) {
        post: markdownRemark(fields: {slug: {eq: $slug}}) {
            html
            frontmatter {
                title <------ NOT NAME
            }
        }
    }
```
