### ISSUE TITLE
node.html works but not node.excerpt for page

### ISSUE THREAD

**Issue by linoxyn** [cedricdelpoux/gatsby-source-google-docs#44]
As in how one builds out a main blog page and then having `blog/posts`, I have the posts pages working well. Though it's the `blog` page that I'm having a problem. I understand that in the structure behind the parse function the first argument needs to be a string. When I use `allMarkdownRemark` and have the query pull the `excerpt `and the `html` I am able to bring in either of their values as long as when I bring in the excerpt I make sure it's inside an HTML element like a <p>. The issue is that the Gatsby <Img> is returned when using the `parse(node.html, options)`  and though I am finding there is no image brought in from using `parse(`<p>${node.excerpt}</p>`, options)`  Thank you for any directions to solve this.

**Comment by cedricdelpoux** [comment]
If you don't have specific use cases on images, Do not use the `parse` function and get the content of the page from `page.html`

**Comment by linoxyn** [comment]
Thank you @cedricdelpoux  this was the trick, to pull the img id string and alt string out of the `page.html` and find the img id against the `googleDocImages.edges.node.id` I was then able to still fully use the Gatsby `<Img />` component.

**Comment by cedricdelpoux** [comment]
You are welcome
