### ISSUE TITLE
token_env_variable issue?

### ISSUE THREAD

**Issue by jodiedoubleday** [cedricdelpoux/gatsby-source-google-docs#45]
Trying to set Environment variables so I can deploy to Netlify.

e.g. token_env_variable: `${process.env.GOOGLE_CLIENT_TOKEN}`,
I'm setting it to exactly what is in my google-docs-token.json file

However when running locally, it still asks me to "Authorize this app by visiting this url.."
so build fail. Any help?

**Comment by justinsunho** [comment]
`token_env_variable` is a string that is your environment variable name. As in the example, `GATSBY_GOOGLE_DOCS_TOKEN` is the name of the environment variable.

in your `.env.*` file it would be: `GATSBY_GDOCS_TOKEN={...}`

**Comment by cedricdelpoux** [comment]
Thank you @justinsunho, you are right. @jodiedoubleday you should prefix you env variables with `GATSBY_` https://www.gatsbyjs.org/docs/environment-variables/

**Comment by loongyh** [comment]
It's only necessary to prefix `GATSBY_` if the env var is to be exposed to client-side browser js. However since we run this plugin during buildtime and not runtime we shouldn't expose it to browser side.
