### ISSUE TITLE
Error - 'source-google-docs:  undefined'

### ISSUE THREAD

**Issue by linoxyn** [cedricdelpoux/gatsby-source-google-docs#46]
I am attempting to implement the latest v2.0.0-beta.1 version. I have the options set as below in the gatsby-config.js

```
{
      resolve: 'gatsby-source-google-docs',
      options: {
        folders: [
          process.env.FOLDER_ID_SHOWS,
          process.env.FOLDER_ID_NEWS,
          process.env.FOLDER_ID_ARTISTS,
          process.env.FOLDER_ID_ARTWORKS,
        ],
        fields: ['ownedByMe', 'shared'],
        fieldsMapper: { createdTime: 'date' },
        fieldsDefault: { draft: false },
        replaceGoogleImages: true,
        debug: true,
      },
    },
    {
      resolve: 'gatsby-transformer-remark',
      options: {
        plugins: ['gatsby-remark-images'],
      },
    },
```
I have paired down my gatsby-node.js to as basic as your "page" example, yet when I run develop I get this error:

```
_object: {
    context: { sourceMessage: 'source-google-docs:  undefined' },
    error: 'failed to process https://lh3.googleusercontent.com/UeJWtsJkT0NjS2TV5hSLhyLtkC25mZXbbHg1t_qK4-XalvYiCa9nC0NhTEz_WYn-nrPN2aXFKVn8niORzmvymbN0IGMX5JPHL-1k6brje763FsrEhftd6bQVzN95LcNmRYfXbX-raOTyuj9iMg\n' +
      'Error: C:\\Projects\\loch\\.cache\\gatsby-source-filesystem\\17e4e820615e428840ed66621b0c6d7d\\GoogleDocsImage-https:\\lh3.googleusercontent.com contains invalid WIN32 path characters.',
    text: 'source-google-docs:  undefined',
    level: 'ERROR',
    stack: [],
    docsUrl: 'https://gatsby.dev/issue-how-to'
  },
```
I assume that when `replaceGoogleImages: true,` is set that the remote images can not use Gatsby Img component using GatsbyImageSharp* though when I use this setting I can query all the data "without remark ecosystem" from my Google Docs and the source URLs for the images without any errors. 

I am not sure how to proceed. Thank you for any help. Something I may be missing?

**Comment by cedricdelpoux** [comment]
It's very strange, I tried with a lot of different setup but I never encounter this. 
Do you have this error with all of your images?
Do you still have the error if you delete this specific image from your google document?
`replaceGoogleImages:true` is enable by default so you don't have to

**Comment by cedricdelpoux** [comment]
But I use MacOS.
The error say `contains invalid WIN32 path characters`. I assume you build using windows. 
That is problematic, I don't have a windows to try to debug this

**Comment by cedricdelpoux** [comment]
I will investigate

**Comment by linoxyn** [comment]
I did some tests by removing the image refereed to in the error message from the Google Doc, though in doing this the next image that is dealt with fails with the same error, therefore ending the `gatsby develop` process.

**Comment by cedricdelpoux** [comment]
@linoxyn Could you try the new `2.0.0-beta.2` version and see if the build still fails?
Thank you for your time

**Comment by linoxyn** [comment]
@cedricdelpoux Thank you for looking into this. I created a new gatsby project with just the essentials and have run the newest `2.0.0-beta.2` I no longer have the error. 

I see that the documentation needs to be updated as the path cannot be queried from `fields`. 
```
post: markdownRemark(frontmatter: {path: {eq: $path}}) {
```
I see that the images that are brought into the project through the `.cache` and that their `gatsby-resp-image-wrapper` and `gatsby-resp-image-link` has set styles and attributes that are generated inside the `html` coming from the Google Docs. This works very well and is the standard usage in a blog format. Though the needs of my site requires a different control over the images as I had in your original Version 1. Is it again possible to query the image source in the `html` to query the filename again by using `allFile` to use `childImageSharp` and the gatsby `<Img />` component? Are there any suggestions of what to be watchful for that may be different in this beta version? 

Again, thank you so much for correcting the error that was being returned on a Windows machine during `build` 💯 Now I can get back to coding this project.

**Comment by cedricdelpoux** [comment]
The best way to query with `path` without add an extra field is to query `googleDocs` and use `childMarkdownRemark` which is equivalent to 
```
post: googleDocs(document: {path: {eq: $path}}) {
      document {
        name
        createdTime
      }
      childMarkdownRemark {
        html
      }
    }
```

**Comment by cedricdelpoux** [comment]
@linoxyn please checkout the `2.0.0-beta.3` version. 

I also updated the FAQ. You can see how to query images only https://github.com/cedricdelpoux/gatsby-source-google-docs/blob/master/docs/faq.md#how-can-i-query-images-only

**Comment by cedricdelpoux** [comment]
I close this issue. Please comment and reopen an other if you need it :)
