### ISSUE TITLE
How to parse code blocks?

### ISSUE THREAD

**Issue by rsbh** [cedricdelpoux/gatsby-source-google-docs#47]
I have some docs with [Code Blocks](https://gsuite.google.com/marketplace/app/code_blocks/100740430168) how to generate html from that as it comes as table tag

**Comment by cedricdelpoux** [comment]
Do you have an error when you build? What is the actual output?

**Comment by rishabh09** [comment]
I am getting code block as table with 1 column and 1 row, can we parse it as code tag

**Comment by cedricdelpoux** [comment]
I just tried it and the plugin create tables in Google Docs so it is normal that this plugin create tables as well.

<img width="657" alt="Screenshot 2020-03-10 at 11 11 39" src="https://user-images.githubusercontent.com/2683300/76302264-f3fde600-62bf-11ea-8765-08109f528585.png">

I could be nice to transform that to code tags but we need to detect in some way that it is a code block.

I'm opened to pull requests. Is could be awesome if you could help me about this :)

**Comment by rishabh09** [comment]
@cedricdelpoux as far as I know it creates a table with 1 row and 1 column. other than that I didn't find anything on the output JSON

**Comment by cedricdelpoux** [comment]
I made some research and the best solution should be to use a plugin to embed an external service like [codepen](https://github.com/octahedroid/gatsby-remark-codepen), [codesandbox](https://github.com/elboman/gatsby-remark-embedded-codesandbox), [Github gist](https://github.com/weirdpattern/gatsby-remark-embed-gist) or an other one.

I closes this issue but if you found a way to handle this, please make a PR 😊

**Comment by cedricdelpoux** [comment]
Hi @rsbh!
Just to let you know that `Code Blocks` support has be added in the last release `2.0.0-beta.22`.

You can find how to use it in the [documentation](https://github.com/cedricdelpoux/gatsby-source-google-docs/blob/master/docs/faq.md#how-can-i-add-code-blocks)

**Comment by rsbh** [comment]
i think adding support for codeblock should be from config, it should be false by default and user has to know what codeblock is and he/she cant create any other table with 1 cell if they are using codeblock

**Comment by cedricdelpoux** [comment]
I thinked about it a lot. That's why I could not support it in the first place.
Do you know any usecase with 1 cell tables?

**Comment by rsbh** [comment]
I dont think of any particular usecase, but this feature is overriding the default behaviour, and should be behind the flag to turn on/off.

**Comment by cedricdelpoux** [comment]
Thank you for your feedback I will think about it. 

If you built your site using `gatsby-source-google-docs`, please add it to the [showcase](https://github.com/cedricdelpoux/gatsby-source-google-docs/blob/master/showcase.yml) 🙂

**Comment by cedricdelpoux** [comment]
I update the condition to separate code blocks and tables. 
I found that if the `Code Blocks` google docs extension format the table, the font family of every text element is `Consolas`.
It will be published in the next release.
