### ISSUE TITLE
Generated no Gatsby nodes

### ISSUE THREAD

**Issue by josephricafort** [cedricdelpoux/gatsby-source-google-docs#48]
Hi! Thanks for this wonderful plugin! Currently figuring out to make it work. This is actually an issue for the gatsby-google-docs-source-team plugin but I assume these are both having the same base?

I have setup the gatsby-config.js and generated a token successfully but it seems that I am not able to source from the google drive properly although it doesn't throw any error but only a warning.

<img width="770" alt="Screenshot 2020-03-10 at 11 32 43 PM" src="https://user-images.githubusercontent.com/12780821/76329415-82598280-6327-11ea-917d-22a8f18c2451.png">

I am also checking GraphiQL to see whether I'd be able to query but I cannot see "googleDocs" available to query.

Been checking for other issues but haven't found related to this. Any thoughts?

**Comment by cedricdelpoux** [comment]
@josephricafort I think you use thee wrong plugin.

On your screenshot, I can see `gatsby-source-google-docs-team` instead of  `gatsby-source-google-docs`.

Please try the good one and reopen a new issue if you have problems
