### ISSUE TITLE
Not able to query "google-docs-image-**"

### ISSUE THREAD

**Issue by linoxyn** [cedricdelpoux/gatsby-source-google-docs#53]
The generated static image files now in Version 2.0.0-beta.4 are being saved without the prefix google-docs-image-** Here is an example of one of the images saved from from the Doc. The same jpg file name references are found as well in the html generated.

```
public\static\0fb3447c14bb429cf54e0499664270f7\c989d\nQa9_MHAbJJkG8b4NOiGiYoAHq1nhxRFqo4NdKgayIdn-TR0QFvrZhRPsC57A72ylQJUwEn2ucpvbrHtArGxC8VXyDEybz_yKCFrweOvtswTIvoDHiEb-rQlOf8U5NGFKqctV0H0lZ1H_1SpLQ.jpg
```

**Comment by cedricdelpoux** [comment]
You are right, I just fixed it in `2.0.0-beta-5` version.

Thank you for reporting this.

I'm very curious to know your usecase.

Do you need to add a cover to your posts?
Otherwise, [you can do it](https://github.com/cedricdelpoux/gatsby-source-google-docs/blob/master/docs/faq.md#how-can-i-add-a-cover)

**Comment by linoxyn** [comment]
Thank you for the update version, I will update my project later today.

I use the Docs in different ways within this project though I have many Google Docs that are queried for one image (a few have two images so I'm not sure if two images can be placed and queried in the Doc's header), there is text, which becomes html content in the Docs in each of these specific Docs which is generated by a Google App Script from a Google Sheet. In these cases the needed text data is solely queried from the Doc's Description Fields, so generally the html content of the Doc is not always used (It is there for an input user so they are not confused about creating content).. I may test out this **'cover'** solution as I may not then have any need to extract the images filenames out of the html to `find()` them within an `allfile` query. 

Thank you!

**Comment by cedricdelpoux** [comment]
It's interesting. Thank you for your feedback 🙂

**Comment by linoxyn** [comment]
Cedric, I cannot seem to query `cover` within the GraphiQL explorer to access `...GatsbyImageSharpFluid`.  I have removed the images from the body of the Google Docs and therefore now these images have been added to the header section in each case.  The `html` content is correct as it does not contain the image information that should now be residing in the `header`.

Is there a setting in `gatsby-config.js` or some code in the `gatsby-node.js` that is needed to be changed in order for the `cover` field to be available?

```
export const pageQuery = graphql`
  query BlogPost($path: String!) {
     post: markdownRemark(fields: {path: {eq: $path}}) {
        html
       frontmatter {
         cover {  <------- **This field does not show?**
           ?
          }
       }
     }
  }
`
```
Thank you

**Comment by cedricdelpoux** [comment]
Try "First page different": 
<img width="865" alt="Screenshot 2020-04-02 at 16 51 48" src="https://user-images.githubusercontent.com/2683300/78263456-45397800-7502-11ea-91e6-fa83dbce8b2d.png">

**Comment by linoxyn** [comment]
Thank you for your reply Cedric. I have updated the Docs so all cover images in the header are set as **First Page Different**. I now am getting this error:
```
UNHANDLED REJECTION Cannot destructure property 'inlineObjectId' of 'element.inlineObjectElement' as it is undefined.

[gatsby-source-google-docs]/utils/converters.js:55:5
```
Could this be because not all Docs contain an image in the header, therefore undefined?

Thank you.

**Comment by cedricdelpoux** [comment]
could you share with me a Google Document to reproduce?

**Comment by cedricdelpoux** [comment]
Please continue the discussion here #55

**Comment by linoxyn** [comment]
@cedricdelpoux  
This is one of the shared folders, not all have an image in the header.

```
{
      resolve: "gatsby-source-google-docs",
      options: {
        folders: ["16X-9dU4dEq_F3CprJQN-4l0WiaYeW_hg"],
        debug: true,
      },
    },
```
