### ISSUE TITLE
cannot generate token " not recognized as an internal or external command"

### ISSUE THREAD

**Issue by ecomloop** [cedricdelpoux/gatsby-source-google-docs#54]
I'm attempting to generate a token and getting an error stating "'gatsby-source-google-docs-token' is not recognized as an internal or external command,"

I'm new to Gatsby and would appreciate any help. Per instructions, I have downloaded, then attempted to generate token using 'gatsby-source-google-docs-token'.

**Comment by shaunchander** [comment]
You need to add `gatsby-source-google-docs-token` as a script in your package.json file and then use either NPM or Yarn to run that command, for example:

```
"scripts": {
    "genToken": "gatsby-source-google-docs-token"
}
```


You would then go into your terminal and run `npm run genToken` or `yarn genToken` depending on what package manager you're using.

**Comment by cedricdelpoux** [comment]
I will add this to the documentation! Thank you

**Comment by cedricdelpoux** [comment]
Please checkout the documentation

https://github.com/cedricdelpoux/gatsby-source-google-docs/blob/master/docs/token.md#gatsby-source-google-docs-token-is-not-recognized-as-an-internal-or-external-command

**Comment by ecomloop** [comment]
thanks for the help @shaunchander and appreciate the update to the documentation @cedricdelpoux
