### ISSUE TITLE
Request - return a collection of images from the 'cover'

### ISSUE THREAD

**Issue by linoxyn** [cedricdelpoux/gatsby-source-google-docs#59]
A request - At the moment it is only possible to return one image from the header of a Google Doc using the `cover` query. Would it possible to return a collection (array) of multiple images from the when multiple images are inserted into a Google Doc Header?

**Comment by cedricdelpoux** [comment]
Could you give me your usecase?
Do you need some gallery for your post? In this case maybe we can collect all images from the post

**Comment by linoxyn** [comment]
The advantage of the `cover` query is that it's much less code which helps simplify the templates/pages. 

The people who will edit the Google Sheets and Docs for the most part will only need work within these without much need at all to understand markdown. Pages that get generated from the Docs come from employing the templates and also by data queries from other supportive Google Docs. For most template page generation one main or thumbnail Gatsby `Img` is all that's needed, though there are times when two or more may be needed. 

My main project is a commercial art gallery site.

For example:

Index page/One artist type category out of 3 (with one or more header images)/list of artists in that category (with one or more header images)/One artist including a biography (with one or more header images), available artworks(with one or more images), and sold sections of artworks (with one or more images)

In the last stage of this example there is a Google Doc for each artist (including one or more images), and a Google Doc for each artwork (including one or more images). Most artwork, for example a painting only requires one image, though sculpture may require multiple images. 

My project is currently coded not using the `cover` query though if this could return multiple images I could then easily use ...GatsbyImageSharp plus I believe that would work better as I could then separately query the images inserted into the returned html body of the Docs from the header `cover` images. 

I am not using the blog style onClick images where the image opens in a new tab.

The images on this gallery site either route to another page or open an overlay model with next and previous navigation.  

thank you😊

**Comment by cedricdelpoux** [comment]
Ok I understand. It will be most a `images` data and not a `cover` anymore.

Can I see what treatment do you do to retrieve all images actually?

**Comment by linoxyn** [comment]
This is one of the more simple examples as part of an **About** page. It allows me to take the images references out of the `html` and then use `Img` to place and style the collection into i.e. a `div` element on the page.  I too can query one image, the first, out of that array to show on a navigation card from another 'posts' page if I choose. 

The structure needed/wanted by the client would determine the structure of the Docs and or Google Sheets that are edited.  

```
const About = ({ data: { intro, tor, googleDocImages } }) => {
  const regLine = /(^<p><span[\s\S]*?<\/span><\/p>$)/gm
  const imgLine = /(?=google-docs-image)([\s\S]*?)(?=\.)/gm
  const introHTML = intro.html
  const torHTML = tor.html
  const cutIntroHTML = introHTML.replace(regLine, '')
  const torImgs = torHTML.match(imgLine)
  let imgTorArr = [...new Set(torImgs)]

  const torImg = imgTorArr.map((item, i) => {
    let fndImg = googleDocImages.edges.find(({ node }) => node.name === item)
      .node.childImageSharp.fluid
    return (
      <div key={item}>
        <Img
          fluid={fndImg}
          alt={`Toronto Gallery ${i}`}
          style={{
            height: 'auto',
            minWidth: fndImg.presentationWidth,
          }}
        />
      </div>
    )
  })

  return (
    <Layout>
      <SEO title={intro.frontmatter.page} />
      <TitleDiv>
        <h3>{intro.frontmatter.page}</h3>
        <h1>{intro.frontmatter.name}</h1>
      </TitleDiv>
      <PostDiv dangerouslySetInnerHTML={{ __html: cutIntroHTML }} />
      <PostDiv dangerouslySetInnerHTML={{ __html: torHTML }} />
      <PostDiv>
        <ImgsDiv>{torImg}</ImgsDiv>
      </PostDiv>
     </Layout>
  )
}

export default About

export const query = graphql`
  query {
    site {
      siteMetadata {
        title
      }
    }
    intro: markdownRemark(
      frontmatter: { page: { eq: "About" }, about: { eq: "intro" } }
    ) {
      id
      html
      frontmatter {
        about
        page
        name
        heading
      }
    }
    tor: markdownRemark(
      frontmatter: { page: { eq: "About" }, about: { eq: "Toronto" } }
    ) {
      id
      html
      frontmatter {
        about
        page
        name
        heading
      }
    }
    googleDocImages: allFile(
      filter: { name: { glob: "google-docs-image-**" } }
    ) {
      edges {
        node {
          id
          name
          childImageSharp {
            fluid(maxWidth: 300) {
              ...GatsbyImageSharpFluid
              presentationWidth
            }
          }
        }
      }
    }
  }
`
```

**Comment by cedricdelpoux** [comment]
Yes it's painfull.

It's a good idea to return all images instead of the first one. 
`images` field will replace the `cover` field.

We could still use the first one for the cover if we need too.

Do you want to help me on this?

**Comment by linoxyn** [comment]
It would maybe add more flexibility if the header and body could separately return all images (two sets). 

from `converters.js`
```
const headerElement = _get(headers[documentStyle.firstPageHeaderId], [
    "content",
    0,
    "paragraph",
    "elements",
    // 0, This removed returns objects that contain the collections of image inlineObjectId(s)
  ])
```
The one or more header `inlineObjectElement: { inlineObjectId: 'kix.hk4a5qjvgg39', textStyle: {} }`  **inlineObjectId** would need to be matched with  `inlineObjects` in order to get all the `contentUri` and image properties. I figure this is possible to do though it's a complex bit of coding.

**Comment by cedricdelpoux** [comment]
I would do:

```
const headerElements = _get(headers[documentStyle.firstPageHeaderId], [
    "content",
    0,
    "paragraph",
    "elements",
  ])

  const headerImages = headerElements.map(element => getImage(document, element))
```

**Comment by cedricdelpoux** [comment]
@linoxyn I can't hardly add multiple images in the header because the height is limited and all other images are hidded. Do you have any tips? Did you success?
<img width="853" alt="Screenshot 2020-08-11 at 08 22 36" src="https://user-images.githubusercontent.com/2683300/89864338-0ef4bf00-dbac-11ea-896a-7ab22335142a.png">

**Comment by cedricdelpoux** [comment]
I can reduce each image size to fit but it's not ideal and pretty limited

**Comment by linoxyn** [comment]
I believe that Google doesn't really want a user to use too many images within the header. The ability to query just one image in the header is probably best to stay at this limit. Thank you for looking into this though I believe this request could be closed.

**Comment by cedricdelpoux** [comment]
Yes sorry! Please reopen if you have an other idea in the future

**Comment by cedricdelpoux** [comment]
Hi @linoxyn, please checkout the new `v2.0.0-beta.17`. 
I added the images from the content of any document in the frontmatter

**Comment by linoxyn** [comment]
@cedricdelpoux  I think you have made my day! Big smiles!!!! 😊 I've yet to test this in development though seeing the access to images and content in the frontmatter  looks like a gamechanger! Thank you! This will simplify many of the components and page templates I've built... lots of editing ahead of me!

**Comment by cedricdelpoux** [comment]
You are welcome. Enjoy !
