### ISSUE TITLE
Use Gatsby cache to be Gatsby cloud compliant

### ISSUE THREAD

**Issue by cedricdelpoux** [cedricdelpoux/gatsby-source-google-docs#60]
Now, we use a home made cache solution and store all data in `.google` folder but it's not idea for Gatsby Cloud

**Comment by linoxyn** [comment]
Hi Cedric, did you mean `.cache\caches\gatsby-source-google-docs` instead of `.google` ? I had thought the `.google` folder was only used for the `token.json` file? 

Is this cache created at build time?

**Comment by cedricdelpoux** [comment]
Yes only the token. It's possible on Netlify using the plugin `gatsby-plugin-netlify-cache` but I don't know how to do this with Gatsby Cloud. I opened a issue https://github.com/gatsbyjs/gatsby/issues/24109

**Comment by cedricdelpoux** [comment]
Updates are be made. `gatsby-source-google-docs` is now using the `gatsby` cache
