### ISSUE TITLE
Support for Footnotes

### ISSUE THREAD

**Issue by archydeberker** [cedricdelpoux/gatsby-source-google-docs#65]
Thanks for this awesome plugin, it's a wonderful idea.

I'm trying to render footnotes from Google Docs, but I can't see them exposed in GraphQL. They're absent from both the `content` and `markdown` attributes; are they exposed by the Google Docs API?

Thanks!

**Comment by archydeberker** [comment]
I've been digging around a little and it looks like I can parse the footnotes in this function https://github.com/cedricdelpoux/gatsby-source-google-docs/blob/9ae6697ae50c7c908c6a61978adac7e19d394130/src/utils/converters.js#L155, since they are indeed returned by the Google Docs API.

I will try and hack this for myself and then I can open a PR if you this is useful.

**Comment by linoxyn** [comment]
Do you mean the JSON data you can write into the `Details/Edit description` for the specific Google Doc? Found in the side panel when you highlight a Doc in a folder. Anything you put into the description can be queried very easily using the GraphiQL interface and then by using that query in your code. I hope that helps?

**Comment by cedricdelpoux** [comment]
@archydeberker What do you mean about footnotes? Like @linoxyn said, you can add any information in the "description" field from google drive. You need to put a valid JSON object.

I'm interested about your usecase to improve this plugin. Can you tell me more?
Thank you for helping me. PR are always welcome 🙂

**Comment by archydeberker** [comment]
Thanks for the interest.

We want to be able to display footnotes from Docs using Gatsby.

In Markdown, footnotes are presented in the main text as [^1], [^2], along with the references below ([^1] This is the content of the first footnote, [^2] This is the content of the second footnote) - see https://www.markdownguide.org/extended-syntax/#footnotes.

I actually managed to make this work yesterday - you can have a look at the result [here](https://xenodochial-allen-667626.netlify.app/using-subjective-well-being-to-estimate-the-moral-weights-of-averting-deaths-and-reducing-poverty)  (I used [Littlefoot](https://github.com/goblindegook/littlefoot) for the formatting of the footnotes).

If you think this is interesting/useful for others, I will happily open a PR. I merely added some functionality to https://github.com/cedricdelpoux/gatsby-source-google-docs/blob/9ae6697ae50c7c908c6a61978adac7e19d394130/src/utils/converters.js#L155

I'll open a PR so you can have a look.

**Comment by cedricdelpoux** [comment]
It looks great! Nice work 👏🏻

Once your website will be published, you can add you website in the [showcase](https://github.com/cedricdelpoux/gatsby-source-google-docs/blob/master/showcase.yml) if you like. It is empty for now but we need to start somewhere!

**Comment by cedricdelpoux** [comment]
@archydeberker I merged the PR but I found that the tests were broken. I push a fix to add a default value in case there is no footnotes. If you are still motivated and you want to add some footnotes in the tests, you are welcome. Otherwise, no problem I will add some later

**Comment by cedricdelpoux** [comment]
Footnotes are published in `2.0.0-beta.14`
