### ISSUE TITLE
Did the changes recently to Google's Drive/Docs affect this plugin?

### ISSUE THREAD

**Issue by linoxyn** [cedricdelpoux/gatsby-source-google-docs#67]
I have recently got back to working on a project that uses `gatsby-source-google-docs` in an image gallery style Gatsby site. I should state that for the most part one image per document is often all that is needed. To use the images from the Docs in the project I am using `allFile` query of `google-docs-image-**` to find the `Img` nodes instead of relying on the 'blog' style `gatsby-resp-image-wrapper` inside the html.  I have now noticed that if I had added two or more images to the body of a Google Doc, that only the first image is using the `gatsby-resp-image-wrapper` and the remaining images are using the Drive's direct source for the file, for example - `src="https://lh3.googleusercontent.com/_LSRmVb6wHB...etc` The query for `markdownRemark.html` clearly shows this, so everywhere in my project where the code used to handle multiple images in one document now only handles the first. This is important for those times when more than one image is needed.

I have tried to see what may have changed and so far all I can tell based on the GraphQL queries it might be that something has changed with the structure of Google's Docs? I would like to know if others have noticed this?

**Comment by cedricdelpoux** [comment]
It's strange. Do you think this bug was here since a long time? Could you try to use an old version of `gatsby-source-google-docs` to check?

Thank you

**Comment by cedricdelpoux** [comment]
I could reproduce. Could you try `gatsby-source-google-docs@2.0.0-beta.14`?

**Comment by linoxyn** [comment]
Thank you so much @cedricdelpoux the updated `gatsby-source-google-docs@2.0.0-beta.14` has resolved the issue, now all images in the body are being handled by the plugin! 👍
