### ISSUE TITLE
using lastModifyingUser results in a query error

### ISSUE THREAD

**Issue by forivall** [cedricdelpoux/gatsby-source-google-docs#68]
My fields config:

```js
fields: ['properties', 'lastModifyingUser/displayName', 'webContentLink', 'webViewLink'],
```
Based on my reading of [google's docs](https://developers.google.com/drive/api/v3/fields-parameter) [(and the available fields for google docs files)](https://developers.google.com/drive/api/v3/reference/files#resource-representations), I've also tried `'lastModifyingUser(displayName)'`, `'lastModifyingUser.displayName'` and `'lastModifyingUser'`, with these results:

```
There was an error in your GraphQL query:

Field "lastModifyingUser" of type "GoogleDocsDocumentLastModifyingUser" must have a selection of subfields. Did you mean "lastModifyingUser { ... }"?
```

and if i specify `lastModifyingUser { displayName }`, i get

```
  Error: Invalid field selection files(id, mimeType, name, description, createdTime, modifiedTime, star  red, properties, lastModifyingUser { displayName }, webContentLink, webViewLink)
```

**Comment by cedricdelpoux** [comment]
Did you tried to run the query in graphiql to explore the schema ?

**Comment by forivall** [comment]
I havent had time to check yet. thanks for the tip.

**Comment by forivall** [comment]
`'lastModifyingUser(displayName)'` now works.

```graphql
query MyQuery {
  allGoogleDocs {
    edges {
      node {
        breadcrumb
        path
        lastModifyingUser {
          displayName
        }
      }
    }
  }
}
```
