### ISSUE TITLE
Processing Error - gatsby develop

### ISSUE THREAD

**Issue by linoxyn** [cedricdelpoux/gatsby-source-google-docs#69]
Here is the error output:
```
Processing C:/Projects/lochwebsite/.cache/caches/gatsby-source-google-docs/40ddb3df04d7c5a8a0473e6bf801d4b2/google-docs-image-4d7218b8-316a-5853-aab9-4663599dcda2.png failed

Original error:

  WorkerError: Processing C:/Projects/lochwebsite/.cache/caches/gatsby-source-google-docs/40ddb3df04d7c5a8a0473e6bf801d4b  2/google-docs-image-4d7218b8-316a-5853-aab9-4663599dcda2.png failed
  Original error:

  - jobs-manager.ts:318 enqueueJob
    [lochwebsite]/[gatsby]/src/utils/jobs-manager.ts:318:21

  - runMicrotasks

  - task_queues.js:97 processTicksAndRejections
    internal/process/task_queues.js:97:5

not finished Generating image thumbnails - 140.317s
```
I tried reverting to the `2.0.0-beta.17` version though this did not change the error. I even tried to remove the Google Doc and the associated image that was returning the error only to have a different image go into the same error. I'm not sure where this error is coming from though I did update a few packages, none should have had any breaking changes, just regular updates to eslint, gatsby, and gatsby-cli, etc. 

Thank you :)

**Comment by linoxyn** [comment]
I have been trying to find a state where I can get the images to get generated and found if I set an older `gatsby-plugin-sharp@2.6.29` version it works. Hope that helps.

**Comment by cedricdelpoux** [comment]
It's very strange. I don't know where to start to resolve this one

**Comment by linoxyn** [comment]
I keep hoping that the newest packages updates fixes this issue, though so far the older version of  `gatsby-plugin-sharp@2.6.29` is the only way to get the `gatsby develop` to run all the image nodes without the above error. If something gets fixed in this plugin in a newer version I'll let you know.  

It might be related to [this issue on Gatsby](https://github.com/gatsbyjs/gatsby/issues/26765):

**Comment by cedricdelpoux** [comment]
I hope so. `gatsby-source-google-docs` depend on `gatsby-source-filesystem` to fetch and create remote images nodes
