### ISSUE TITLE
Gatsby Img from childMarkdownRemark not formatted in html

### ISSUE THREAD

**Issue by linoxyn** [cedricdelpoux/gatsby-source-google-docs#72]
Since I believe `v2.0.0-beta.21` The `html` returned in the `allGoogleDocs { nodes { childMarkdownRemark { html }}}` now no longer formats any Gatsby Img. I believe I have the `gatsby-config` file set properly for all plugins. Is this an expected change in the newer versions? In my use case I was leaving in the extra, after the first, Gatsby Imgs to some of the generated pages content. I could change my code to handle the remaining images with childImageSharp, though for now the places I am expecting the Gatsby Imgs to render, the html content shows a broken image icon.

This is one part of a returned query showing the `html` :
```
        .....},
            {
          "images": [
            {
              "childImageSharp": {
                "fluid": {
                  "src": "/static/9b1c5e9e038eb6a5331765b1b65108d2/ee604/google-docs-image-7c430eb2-680e-576d-be56-2b5f5d49d1ff.png"
                }
              }
            },
            {
              "childImageSharp": {
                "fluid": {
                  "src": "/static/c49446a06709af5cb7f8690051fcdba3/ee604/google-docs-image-9f132562-b8bb-5e85-a4c1-cc80ed736ac8.png"
                }
              }
            }
          ],
          "childMarkdownRemark": {
            "html": "<p><img src=\".cache/caches/gatsby-source-google-docs/02f0d2b7da84c90500b9a85d278be615/google-docs-image-7c430eb2-680e-576d-be56-2b5f5d49d1ff.png\"></p>\n<p>The Gallery is delighted to announce that <a href=\"/established-living-contemporary/shannon-cray\">Shannon Cray</a> will be featured in the Spring issue of “In View” magazine, published by the Dulwich Picture Gallery, London, ..... painting in person.</p>\n<p>Please click on the image below to see a larger version of the article.</p>\n<p><img src=\".cache/caches/gatsby-source-google-docs/4f91ad108eb8b4aaf0356a2b22318327/google-docs-image-9f132562-b8bb-5e85-a4c1-cc80ed736ac8.png\"></p>"
          },
          "name": "Shannon Cray: Featured in the Dulwich Picture Gallery's \"In View\" magazine"
        },
        }.......
```

**Comment by cedricdelpoux** [comment]
Thank you for reporting this bug. I will try to understand what happen

**Comment by cedricdelpoux** [comment]
I think I found the bug! 
Could you try the new `2.0.0-beta.24` version?

**Comment by linoxyn** [comment]
Yes, thank you! The new `2.0.0-beta.24` version fixes this issue.

**Comment by cedricdelpoux** [comment]
Perfect!
It could be good to add some tests to this part, but it's depending on other plugins so I don't know if it's possible. Do you have some tests skills?

**Comment by linoxyn** [comment]
I am sorry, I do not have much practice using tests... something I keep neglecting :D

**Comment by cedricdelpoux** [comment]
No problem, I will add some tests
