### ISSUE TITLE
Problem installing package

### ISSUE THREAD

**Issue by liroliro** [cedricdelpoux/gatsby-source-google-docs#81]
While trying to use this, after declaring and installing it, the package still is missing in node_modules.

```
ERROR #10226  CONFIG

Couldn't find the "gatsby-source-google-docs" plugin declared in "*/demo/gatsby-config.js".

Tried looking for a local plugin in */demo/plugins/gatsby-source-google-docs.

Tried looking for an installed package in the following paths:
 - /node_modules/gatsby/dist/bootstrap/load-themes/node_modules/gatsby-source-google-docs
 - /node_modules/gatsby/dist/bootstrap/node_modules/gatsby-source-google-docs
 - /gatsby/dist/node_modules/gatsby-source-google-docs
 - /node_modules/gatsby/node_modules/gatsby-source-google-docs
 - /node_modules/gatsby-source-google-docs

```

**Comment by cedricdelpoux** [comment]
Could you try to reinstall using `yarn add gatsby-source-google-docs`?

**Comment by liroliro** [comment]
Same result. Updated gatsby to 2.24.74, and tried the same and got a different result. 

`
 ERROR 

source-google-docs: There is no such converter: value
`

**Comment by cedricdelpoux** [comment]
This time it's not the same error. The package `gatsby-source-google-docs` was found.

I'm can't reproduce. 

Could you share with me the Google Document you use or could you try to use it with a very simple Google Document?

**Comment by liroliro** [comment]
I figured it out via your last comment!
The issue here that I wasn't connected to a specific folder, which resulted in the server crashing cause it didn't get any data.

Thanks!

**Comment by cedricdelpoux** [comment]
Ok good to know!

It should not happen anyway. I will try to reproduce and fix it. Thank you for reporting this
