### ISSUE TITLE
Font sizes are getting ignored

### ISSUE THREAD

**Issue by somoy99** [cedricdelpoux/gatsby-source-google-docs#83]
Hi, I just started to use this package and I think it's really cool. Here's one problem I'm having, no matter whatever the font I'm setting in the sheet it's getting ignored. I also tried with markdown syntax like `#` but it's getting ignored as well. 

```json
    "gatsby-source-google-docs": "^2.0.0-beta.26",
    "gatsby-transformer-remark": "^2.8.42",
    "gatsby-transformer-sharp": "^2.5.7",
    "react": "^16.12.0",
    "gatsby": "^2.23.12",
```

**Comment by somoy99** [comment]
Ah... I was using bulma, not using `content` to wrap it. pretty dumb.

**Comment by cedricdelpoux** [comment]
The font size you set in your *Google Docs* documents are ignored for now to keep the html as clean as possible. Do you think it could be nice to support it?

**Comment by somoy99** [comment]
I think it'd be useful to at least support heading 1, 2, 3. I'm trying to set up a blog where most of the writers are quite non technical, they could totally skip markdown syntax that way.

**Comment by cedricdelpoux** [comment]
Headings are fully supported! 
You can add heading 1, 2,, 3, 4, 5, 6.
Do you have a problem using it?

**Comment by somoy99** [comment]
> The font size you set in your _Google Docs_ documents are ignored for now to keep the html as clean as possible. Do you think it could be nice to support it?

sorry, by font size getting ignored I thought we are dropping support for headings as well. 
Nope, I have no problem using headings. 
Not sure if I'd need different font sizes for normal texts, if I wanted to change the font size of all normal text, I could add css for `p` tags. 

btw. what kind of changes are to be expected in html if we want to support it?

**Comment by cedricdelpoux** [comment]
we could add an `<span style="font-size:12px">` html tag around text in the `formatText` function [here](https://github.com/cedricdelpoux/gatsby-source-google-docs/blob/master/utils/google-document.js#L124-L126).

But I don't want to enable this feature by default and should be enabled with an option *enableFontSize*.
Finally, we need to update existing tests to add this new feature

**Comment by somoy99** [comment]
`enableFontSize` that'd be clean. I'm not having any use case for it yet, but I think someone at some point would re-open this, it could be nice to support it.

**Comment by somoy99** [comment]
I can attempt to do it over the weekend, not really familiar with the plugin creation eco-system though, want to give it a shot

**Comment by somoy99** [comment]
@cedricdelpoux something like this ? didn't try it out though

**Comment by cedricdelpoux** [comment]
Finally, the `enableFontSize` option is not needed.
I used `em` unit relative to normal text font size. 

Example:
normal text in 11 in Google Docs
if you set other text with 12, it will add a `<span style="font-size: 1.09 em">` tag around the text

**Comment by cedricdelpoux** [comment]
Thank you for your work @somoy99

**Comment by tahmid-shahriar-lincx** [comment]
Sorry I wasn't much of help
