### ISSUE TITLE
source-google-docs: There is no such converter: value

### ISSUE THREAD

**Issue by stevebauman** [cedricdelpoux/gatsby-source-google-docs#87]
Hi there! Thanks for creating this plugin 👍 

I'm encountering an error during the Gatsby build process, exactly like issue #81:

```
ERROR 

source-google-docs: There is no such converter: value
```

My `gatsby-node.js` file is exactly as shown in your documentation:

```js
const path = require(`path`)

exports.createPages = async ({graphql, actions}) =>
graphql(
    `
        {
            allGoogleDocs {
                nodes {
                    document {
                        path
                    }
                }
            }
        }
    `
).then(result => {
    result.data.allGoogleDocs.nodes.forEach(({document}, index) => {
        actions.createPage({
            path: document.path,
            component: path.resolve(`./src/templates/post.js`),
        })
    })
})
```

As well as the `src/templates/post.js` file.

I also ran into another error during the build process:

```
source-google-docs: Cannot destructure property 'rgbColor' of 'backgroundColor.color' as it is undefined.
```

But I was able to side-step it by simply modifying this packages files, namely:

https://github.com/cedricdelpoux/gatsby-source-google-docs/blob/36d5cc68d2e9728d070da84a02d8d885f7e0ef97/utils/google-document.js#L120-L126

I guess in my case, one of my documents doesn't contain the `color` property, so I modified it to this:

```js
if (backgroundColor && backgroundColor.color && !link) {
  const {rgbColor} = backgroundColor.color
  const red = Math.round(rgbColor.red * 255)
  const green = Math.round(rgbColor.green * 255)
  const blue = Math.round(rgbColor.blue * 255)
  styles.push(`color:rgb(${red}, ${green}, ${blue})`)
}
```

Which worked.

Any tips or pointers would be greatly appreciated!

**Comment by cedricdelpoux** [comment]
Hi, thank you for reporting this issue. 

I'm curious to know what property has `backgroundColor` in your case. Maybe it could have `hex` or `hsl` and we have to handle it. 
Could you try to `console.log` or use `yarn doc2test` to write the document structure to your filesystem ?

**Comment by cedricdelpoux** [comment]
The new `2.0.0-beta.30` version should have fixed your color issue. Could you try it?
I hope it will solve your first issue as well

**Comment by cedricdelpoux** [comment]
@stevebauman any news about this?

**Comment by stevebauman** [comment]
Hi @cedricdelpoux, apologies for the late reply -- the latest version has resolved my issues, thanks so much!
