### ISSUE TITLE
Expose formatText Options

### ISSUE THREAD

**Issue by jpoehnelt** [cedricdelpoux/gatsby-source-google-docs#90]
I think it could be beneficial to allow for configuration of the formatText method. Perhaps accepting a string literal or a function such as the following:

```
{
  formatText: {
     italic: `_${text}_`,
     bold: (t) => `**${text}**`
  } 
}
```

**Comment by cedricdelpoux** [comment]
What is your usecase? 
Why do you want to update the italic or bold behaviors?

**Comment by jpoehnelt** [comment]
In cases where elements are used directly, #91.

**Comment by cedricdelpoux** [comment]
So you don't want any **Markdown** syntax, right?

Maybe an option to prefer **HTML** syntax instead of **Markdown** could be an alternative? `<span style="font-weight: bold">` for example.

Could you give me an example of the formatting you expect?

**Comment by cedricdelpoux** [comment]
I close due to inactivity. Please reopen if you need to
