### ISSUE TITLE
Expose raw document and elements in node

### ISSUE THREAD

**Issue by jpoehnelt** [cedricdelpoux/gatsby-source-google-docs#91]
Something like the following would make it easier to customize the usage of the plugin. This would pair well with #90 for using `elements` and potentially bypassing the json2md.

```
const document = googleDocument.document;

const {file, cover, elements} = googleDocument.toObject()

createNode({
...file,
cover,
document,
elements,
})
```

**Comment by cedricdelpoux** [comment]
`elements ` was exposed at first but I fount it confusing. But I agree it could be useful for someone with specific usecase. I will add the data

**Comment by cedricdelpoux** [comment]
`elements` and `document` are now exposed. 
No new version for now before finding the best solution for your other two issues.

I'm very curious to know how you will use these data. Please let me know!

**Comment by cedricdelpoux** [comment]
I remember now while I removed `elements`.
Gatsby gave me this error:

```
warning There are conflicting field types in your data.

If you have explicitly defined a type for those fields, you can safely ignore this warning message.
Otherwise, Gatsby will omit those fields from the GraphQL schema.

If you know all field types in advance, the best strategy is to explicitly define them with the `createTypes` action, and skip inference with the `@dontInfer` directive.
See https://www.gatsbyjs.org/docs/actions/#createTypes
GoogleDocs.elements.value:
 - type: array
   value: [  ]
 - type: object
   value: { number: '1', text: 'cxcxvc' }
 - type: string
   value: 'some string'
```

I tried to explicitly define the schema but did not succeed. Any ideas?
