### ISSUE TITLE
Allow for more flexible whitespace usage

### ISSUE THREAD

**Issue by jpoehnelt** [cedricdelpoux/gatsby-source-google-docs#92]
One of my use cases for this plugin is in supporting poetry docs and specific whitespace patterns such as the following.

```
The poem
    may            have
              strange whitespace
patterns.
```

The plugin works until passing the elements to json2md.

**Comment by cedricdelpoux** [comment]
I did not think about poetry but you are right, it needs to be supported.

For now, there is a way to preserve white spaces is to use a code-blocks because it will be wrapped under `<pre>` tag.

If the issue come from `json2md`. What do you recommend?

**Comment by cedricdelpoux** [comment]
I did a simple test and I understand now.

<img width="304" alt="Screenshot 2020-11-16 at 18 19 03" src="https://user-images.githubusercontent.com/2683300/99285735-3789f600-2838-11eb-8174-ca972a42b4c5.png">

The first solution should be to override the `json2md` convertor for to make this usecase work.
If you want to make a PR for that, it would be awesome

**Comment by jpoehnelt** [comment]
I can make a pr. Might be a while since this is supporting my wife's blog and not my day job. 😄

**Comment by jpoehnelt** [comment]
I think the inherent problem here is that the markdown spec will always interpret the 4 spaces as code. I'm not sure how to go about assigning this some other type given only the number of spaces as this could be desirable behavior for others(converting to code).

**Comment by cedricdelpoux** [comment]
I just verified, `json2md` does not add any `pre` or `code`, so the problem is not this plugin.

It's `gatsby-transformer-remark` that format this way so we have to found a way for `gatsby-source-google-docs` to work without markdown. First, I used markdown because there are a lot of `remark` plugin and it's super useful.

Any ideas?

**Comment by jpoehnelt** [comment]
It's tough because fundamentally markdown is more restrictive than html and thus there will always be some loss of information that is necessary to match the correct rendering.

**Comment by cedricdelpoux** [comment]
The solution may be to write a `gatsby-transformer-google-docs` plugin to transform `elements` to `html` directly

**Comment by cedricdelpoux** [comment]
I close due to inactivity. Please reopen if you need to
