### ISSUE TITLE
Are gatsby-source-google-docs and gatsby-source-filesystem mutually exclusive?

### ISSUE THREAD

**Issue by ilyador** [cedricdelpoux/gatsby-source-google-docs#95]
Once I added `gatsby-source-google-docs` to `gatsby-config` (and changed nothing else in the code) I got the following error:

```
error "gatsby-node.js" threw an error while running the onCreateNode lifecycle:

A plugin tried to update a node field that it doesn't own:

Node id: 2302f6d8-7c9e-54e4-9b06-a60fa5b9e204
Plugin: default-site-plugin
name: slug
value: /my-second-post/

  58 |   if (node.internal.type === `MarkdownRemark`) {
  59 |     const value = createFilePath({ node, getNode })
> 60 |     createNodeField({
     |     ^
  61 |       name: `slug`,
  62 |       node,
  63 |       value


  Error: A plugin tried to update a node field that it doesn't own:
  Node id: 2302f6d8-7c9e-54e4-9b06-a60fa5b9e204
  Plugin: default-site-plugin
  name: slug
  value: /my-second-post/
```
The ID belongs to the `gatsby-source-filesystem` MD imported posts (I get this error for each).
If I understand correctly, gatsby can no longer access my MD files the I used for the blog so far. Why is that?

**Comment by cedricdelpoux** [comment]
Do you have an other `slug` field on your markdown node? 

The purpose of [createNodeField](https://www.gatsbyjs.com/docs/actions/#createNodeField) is to extend an other node.
So I down't know at first why do you have this error.

But good news, I plan to remove this field in next beta release

**Comment by ilyador** [comment]
> Do you have an other slug field on your markdown node?

I don't think so, but not 100% sure. The issue only appeared once I added google-source to the plugin list.
Never had this error before.

Is there a reason I should not be abe to have some pages from MD and some from Google docs?

**Comment by cedricdelpoux** [comment]
There is no reason, I added the `slug` field at first to be compatible with others plugin but it's useless now.

Could you try the last `2.0.0-beta.38`? It should works for you

**Comment by ilyador** [comment]
Thanx, this worked, but now I get 2 different errors:
On build I get
```
error "gatsby-node.js" threw an error while running the onCreateNode lifecycle:

Cannot read property 'replace' of undefined

  75 | 
  76 |   if (node.internal.type === `MarkdownRemark`) {
> 77 |     const value = createFilePath({ node, getNode })
     |                   ^
  78 |     createNodeField({
  79 |       name: `slug`,
  80 |       node,


  TypeError: Cannot read property 'replace' of undefined
```

And when querying `googleDocs`

```graphql
  googleDocs(fields: {slug: {eq: $path}}) {
    name
    childMarkdownRemark {
      html
    }
  }
}
```
I get `Unknown argument "fields" on field "googleDocs" of type "Query"`

**Comment by cedricdelpoux** [comment]
So you have an other `slug` field and there was a conflict. That is why you get the first error.

To query `googleDocs`, you should do 
```
googleDocs(slug: {eq: $path}) {
    name
    childMarkdownRemark {
        html
    }
}
```

because there is no `slug` field anymore.
More info in the [documentation](https://github.com/cedricdelpoux/gatsby-source-google-docs/blob/master/docs/pages.md)

**Comment by ilyador** [comment]
Thanx @cedricdelpoux 
This was solved, however I still get
```
error "gatsby-node.js" threw an error while running the onCreateNode lifecycle:

Cannot read property 'replace' of undefined

  75 | 
  76 |   if (node.internal.type === `MarkdownRemark`) {
> 77 |     const value = createFilePath({ node, getNode })
     |                   ^
  78 |     createNodeField({
  79 |       name: `slug`,
  80 |       node,


  TypeError: Cannot read property 'replace' of undefined
```

In development it works, but in production I cannot deploy because it is an error.

**Comment by cedricdelpoux** [comment]
Are you sure you are using the last version? There are no slug field anymore

**Comment by ilyador** [comment]
I am using 2.0.0-beta.39 like you suggested, but I see slug fields...
Is there another field I should use instead?
This is the query that I use in gatsby-node and it works
```
allGoogleDocs {
  edges {
    node {
      slug
      name
    }
  }
}
```

**Comment by cedricdelpoux** [comment]
When I say there is no `slug` field anymore, I mean you can't query

```
allGoogleDocs {
  edges {
    node {
      fields {
        slug
      }
      name
    }
  }
}
```
But you can query 
```
allGoogleDocs {
  edges {
    node {
      slug
      name
    }
  }
}
```
`slug` is part of GoogleDocs node.

Could you try:
- upgrade to `2.0.0-beta.40`
- run `gatsby clean`
- run `gatsby dev`

**Comment by ilyador** [comment]
I tried `2.0.0-beta.40`. Still getting the same error.

**Comment by cedricdelpoux** [comment]
```javascript
  76 |   if (node.internal.type === `MarkdownRemark`) {
  77 |     const value = createFilePath({ node, getNode })
  78 |     createNodeField({
  79 |       name: `slug`,
  80 |       node,
```
this code does not come from `gatsby-source-google-docs`. You may have an other plugin conflicting.

Could you share a create a minimal reproduction?

**Comment by ilyador** [comment]
I know this is not from `gatsby-source-google-docs` but it started as soon as I added it to the plugin list, so there must be some kind of conflict.

This comes from the gatsby starter and to be honest I'm not 100% sure what it does.
Seems to me like it creates the slug filed that you said no longer exists.

```js
exports.onCreateNode = ({ node, actions, getNode }) => {
  const { createNodeField } = actions

  if (node.internal.type === `MarkdownRemark`) {
    const value = createFilePath({ node, getNode })
    createNodeField({
      name: `slug`,
      node,
      value
    })
  }
}
```

This is the plugin list part that I think might be relevant:
```js
 plugins: [
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        path: `${__dirname}/content/blog`,
        name: `blog`,
      },
    },
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        path: `${__dirname}/content/pages`,
        name: `pages`,
      },
    },
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        path: `${__dirname}/content/assets`,
        name: `assets`,
      },
    },
    {
      resolve: "gatsby-source-google-docs",
      options: {
        folder: "1Ciyh22DLQ9TuIV5cr1u3H1eheKESmDl_",
      },
    },
    {
      resolve: `gatsby-transformer-remark`,
      options: {
        plugins: [
          {
            resolve: `gatsby-remark-images`,
            options: {
              maxWidth: 590,
            },
          },
          {
            resolve: `gatsby-remark-responsive-iframe`,
            options: {
              wrapperStyle: `margin-bottom: 1.0725rem`,
            },
          },
          `gatsby-remark-prismjs`,
          `gatsby-remark-copy-linked-files`,
          `gatsby-remark-smartypants`,
        ],
      },
    },
    `gatsby-transformer-sharp`,
    `gatsby-plugin-sharp`,
```

**Comment by cedricdelpoux** [comment]
Could you give me the link of your gatsby starter?

**Comment by ilyador** [comment]
Sure: https://github.com/gatsbyjs/gatsby-starter-blog/blob/master/gatsby-node.js#L61

**Comment by ilyador** [comment]
Could it be that I don't provide enough information to the docs?
At the moment I did not add any metadata or folder structure, just 2 plain docs.
I'm not sure how to follow these instructions, seems like I need an object to define [these paths](https://github.com/cedricdelpoux/gatsby-source-google-docs#organize-your-documents) but where do I place it?

**Comment by cedricdelpoux** [comment]
> Could it be that I don't provide enough information to the docs?

Metadata are not required. 

You can put your documents in the root folder without nesting tree.

> There was a doc describing all the possible options, but seems like it was removed.

Options are directly in the README now but you have to 
[Click "See options"](https://github.com/cedricdelpoux/gatsby-source-google-docs#add-the-plugin-to-your-gatsby-configjs-file) to see them

**Comment by cedricdelpoux** [comment]
I tried to reproduce but I did not success.

Adding the following to my `gatsby-node.js`
```javascript
exports.onCreateNode = ({node, actions, getNode}) => {
  const {createNodeField} = actions

  if (node.internal.type === `MarkdownRemark`) {
    createNodeField({
      name: `slug`,
      node,
      value: "/test-slug",
    })
  }
}
```
No error and the slug is here

<img width="934" alt="Screenshot 2020-12-17 at 08 30 34" src="https://user-images.githubusercontent.com/2683300/102456878-281de880-4042-11eb-9d12-bed3c4de0d45.png">

**Comment by cedricdelpoux** [comment]
I checked the code of `gatsby-source-filesystem` but I don't find the `replace` that causing issue.

Could you try to put `gatsby-source-google-docs` fist in your list of plugins?
