### ISSUE TITLE
Using shared drives

### ISSUE THREAD

**Issue by ptimson** [cedricdelpoux/gatsby-source-google-docs#98]
I am trying to use a shared drive as my folder. I worked in previous version `2.0.0-beta.15`

Just updated to latest `2.0.0-beta.41` and I get `source-google-docs:  File not found: <dir>`

**Update**
Looks like this issue occurs between 15 and 16 using the new `.env` I tried following migration guide creating new ones but get same issue.

**Comment by cedricdelpoux** [comment]
Hi @ptimson, thank you for reporting this. I tried to reproduce with some shared folders but I can fetch them with the last version.

Could you share your folder with me? cedric.delpoux@gmail.com

**Comment by cedricdelpoux** [comment]
I understood. Shared folders are not shared drives. I don't have a **Google Workspace** subscription so I can't test it.

But I fixed the issue in `2.0.0-beta.42`.

Please reopen if the issue is still here.

**Comment by ptimson** [comment]
Hey @cedricdelpoux thanks for your quick fix. I thought that was the issue but can confirm it's still not working. I've setup and created a shared drive with you to test with 👍  No rush. If I manage to work it will submit a PR. Happy new year!

**Comment by cedricdelpoux** [comment]
Happy new year 🎊 I made my first commit of the year for you !

Thank you for sharing with me your shared drive. It was very easy to reproduce and fix it.

Could you try the last `2.0.0-beta.43` version ?

**Comment by ptimson** [comment]
Works perfectly thank you. Happy new year to yourself - hopefully 2021 will be better! Have one more slight issue but is unrelated so will raise a separate issue. 🤙
