### ISSUE TITLE
Template not found when set createPages to true

### ISSUE THREAD

**Issue by okzapradhana** [cedricdelpoux/gatsby-source-google-docs#99]
I'm having issue with the template if i set the createPages on `gatsby-config.js` to `true`  like code below:
```
module.exports = {
    plugins: [
        {
            resolve: "gatsby-source-google-docs",
            options: {
                // https://drive.google.com/drive/folders/FOLDER_ID
                folder: process.env.GOOGLE_DRIVE_FOLDER_ID,
                createPages: true,
            },
        },
        "gatsby-transformer-remark",
        // You need some transformations?
        // Checkout https://www.gatsbyjs.com/plugins/?=gatsby-remark
        // And pick-up some plugins
    ],
}
```
I'm using dependencies with its version as listed below
```
"dependencies": {
    "gatsby": "^2.26.1",
    "gatsby-source-google-docs": "^2.0.0-beta.44",
    "gatsby-transformer-remark": "^2.14.0",
    "react": "^16.13.1",
    "react-dom": "^16.13.1"
  }
```

I've configure my `.env` with `GOOGLE_OAUTH_CLIENT_ID` , `GOOGLE_OAUTH_CLIENT_SECRET` and `GOOGLE_DOCS_TOKEN` and it looks no problem with that. Also, I've fill the drive folder and file description like the YAML example. I've change the sharing permission URL to public access 

Below are the screenshots of what I've did to my Drive Folder and Files:
![image](https://user-images.githubusercontent.com/22886492/104496414-8cb17080-560b-11eb-9468-2627a165268f.png)
![image](https://user-images.githubusercontent.com/22886492/104496438-98049c00-560b-11eb-9e9f-340f015082a5.png)
![image](https://user-images.githubusercontent.com/22886492/104496485-a488f480-560b-11eb-83a3-0c8e8e23e8c9.png)
![image](https://user-images.githubusercontent.com/22886492/104496532-b2d71080-560b-11eb-8402-900ca0da4a9b.png)
![image](https://user-images.githubusercontent.com/22886492/104497159-8243a680-560c-11eb-8e2d-03624ea1f9e8.png)

But an error raises and said `Template "home" not found. Default template "page" not found.` 
![image](https://user-images.githubusercontent.com/22886492/104497090-6e984000-560c-11eb-81b7-1179ecab746c.png)

Is there any workaround on this problem? Am I missing some steps which leading to this error? 
Any kind of helps will be much appreciated!

**Comment by okzapradhana** [comment]
After doing some logs on `createPages.js` I found the problem which is I haven't create template file at `src/templates/.....js` that leads me to template not found error. But looks like I didnt found the instructions to create file on `templates` folder on this Readme yet.

Anyway, my problem has been solved. Thanks for providing this library! Cheers!

**Comment by cedricdelpoux** [comment]
Yes, you need to create templates in your `src/templates` folder. Checkout [https://github.com/cedricdelpoux/gatsby-source-google-docs/blob/master/example/src/templates/page.js](page template example.)
